
import React from 'react';
import { motion } from 'framer-motion';
import { Cpu, Sparkles, ChefHat, Glasses } from 'lucide-react';
import { useLanguage } from '@/contexts/LanguageContext';

const Features = () => {
  const { lang } = useLanguage();

  const content = {
    fr: {
      subtitle: "Solutions Innovantes",
      title: "L'Avenir de la Restauration",
      features: [
        {
          icon: Cpu,
          title: "Menus Dynamiques",
          text: "Algorithmes prédictifs pour optimiser vos menus en temps réel selon la saisonnalité et les préférences."
        },
        {
          icon: Sparkles,
          title: "Scénographie IA",
          text: "Mise en scène lumineuse et sonore automatisée pour magnifier chaque plat servi."
        },
        {
          icon: ChefHat,
          title: "Créativité Augmentée",
          text: "Des combinaisons d'ingrédients inédites générées par nos modèles d'apprentissage."
        },
        {
          icon: Glasses,
          title: "Expérience Immersive",
          text: "Parcours client personnalisé du premier contact visuel jusqu'à la dernière bouchée."
        }
      ]
    },
    en: {
      subtitle: "Innovative Solutions",
      title: "The Future of Dining",
      features: [
        {
          icon: Cpu,
          title: "Dynamic Menus",
          text: "Predictive algorithms to optimize your menus in real-time according to seasonality and preferences."
        },
        {
          icon: Sparkles,
          title: "AI Scenography",
          text: "Automated lighting and sound staging to magnify every dish served."
        },
        {
          icon: ChefHat,
          title: "Augmented Creativity",
          text: "Unprecedented ingredient combinations generated by our machine learning models."
        },
        {
          icon: Glasses,
          title: "Immersive Experience",
          text: "Personalized customer journey from the first visual contact to the last bite."
        }
      ]
    }
  };

  const t = content[lang];

  return (
    <section id="features" className="relative py-32 bg-black overflow-hidden">
      <div className="absolute inset-0 z-0">
        <img 
          src="https://images.unsplash.com/photo-1508783296529-be0effe57fd2" 
          alt="Modern Restaurant" 
          className="w-full h-full object-cover opacity-15 grayscale mix-blend-overlay"
        />
        <div className="absolute inset-0 bg-gradient-to-b from-black via-transparent to-black" />
        <div className="absolute inset-0 bg-gradient-to-r from-black via-[hsl(var(--accent-purple))]/10 to-[hsl(var(--accent-midnight))]/30" />
      </div>

      <div className="relative z-10 max-w-7xl mx-auto px-6">
        <motion.div 
          initial={{ opacity: 0, y: 30 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.8 }}
          className="text-center mb-20"
        >
          <span className="text-accent-cyan tracking-[0.2em] text-xs font-bold uppercase block mb-4">{t.subtitle}</span>
          <h2 className="text-4xl md:text-5xl font-display text-foreground font-medium">
            {t.title}
          </h2>
        </motion.div>

        <div className="grid md:grid-cols-2 gap-8 lg:gap-12">
          {t.features.map((feature, idx) => (
            <motion.div
              key={idx}
              initial={{ opacity: 0, y: 30 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ delay: idx * 0.1, duration: 0.6 }}
              className="group relative glass-dark rounded-xl p-8 border border-white/5 hover:border-accent-gold/40 transition-all duration-500 overflow-hidden"
            >
              {/* Hover Gradient Overlay */}
              <div className="absolute inset-0 bg-gradient-to-br from-accent-gold/5 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-500" />
              
              <div className="relative z-10 flex gap-6">
                <div className="shrink-0 w-14 h-14 rounded-full border border-white/10 flex items-center justify-center bg-black/50 group-hover:border-accent-cyan group-hover:glow-cyan transition-all duration-500">
                  <feature.icon className="w-6 h-6 text-foreground group-hover:text-accent-cyan transition-colors" />
                </div>
                <div>
                  <h3 className="text-2xl font-display text-foreground mb-3 group-hover:text-accent-gold transition-colors">
                    {feature.title}
                  </h3>
                  <p className="text-foreground-muted/80 font-light leading-relaxed">
                    {feature.text}
                  </p>
                </div>
              </div>
              
              {/* Decorative Corner */}
              <div className="absolute top-0 right-0 w-16 h-16 bg-accent-gold/10 blur-2xl rounded-full opacity-0 group-hover:opacity-100 transition-opacity duration-500" />
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
};

export default Features;
